### ISSUE TITLE
Header/Footers don't use word 'Appendix'

### ISSUE THREAD

**Issue by luciansmith** [sbmlteam/sbmlpkgspec#1]
In the package headers and footers, it always says "Section A" instead of "Appendix A", for example (from the Render spec), the footer of page 63 says "Section A Text Anchor Examples" and the header of page 64 says "Section A.1 Vertical Text Anchor Examples')

**Comment by mhucka** [comment]
Fixed by commit 6e2d9cf3275afd8f3b0bd187a841286d4e644d38

**Comment by luciansmith** [comment]
When I compile the render spec, this ends up being off by one:  I get headers/footers with 'Section 5: Best Practices', but then 'Appendix 6: Future development' (and then 'Appendix A: Text Anchor Examples').

The file I'm using was last updated 9/2 (when I downloaded it), but it has a 'filedate' of 8/16.

**Comment by luciansmith** [comment]
I compiled the qual spec and discovered that the off-by-one problem is off-by-one *page*: in that spec, page 25 has the footer "Section 5: best practices" and page 26 has the footer "Appendix 5: best practices".

**Comment by mhucka** [comment]
I can't seem to replicate the off-by-one error. Attached is my `main.pdf` – can you point me to what I should be looking at?

[main.pdf](https://github.com/sbmlteam/sbmlpkgspec/files/1279194/main.pdf)

**Comment by mhucka** [comment]
From Lucian over Slack just now:

```
The file you sent me has my error as well as other issues.
But my issue can be seen if you look at the bottom of page 62.
It says "Appendix Contents                                    page 62 of 98"
Mine says "Appendix 6  Future Development                         page 62 of 98"
It should say "Section 6  Future Development                         page 62 of 98"
```
